### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by himberjack** [aws/aws-xray-sdk-ruby#40] opened 2019-12-02 19:14 UTC
Aws::Xml::Parser::ParsingError
XML declaration allowed only at the start of the document
--
```
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/xml/parser/stack.rb:45:in `error'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:39:in `error'
/usr/local/bundle/gems/nokogiri-1.10.5/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/usr/local/bundle/gems/nokogiri-1.10.5/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
/usr/local/bundle/gems/nokogiri-1.10.5/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:13:in `parse'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/xml/parser.rb:34:in `parse'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/response/body.rb:43:in `parse'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/response/body.rb:23:in `apply'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/response/parser.rb:32:in `extract_body'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/response/parser.rb:12:in `apply'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/handler.rb:9:in `block in call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/response.rb:45:in `block in on'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/http/response.rb:144:in `block in on_success'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/http/response.rb:171:in `block in listener'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/http/response.rb:135:in `on_done'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/http/response.rb:142:in `on_success'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/response.rb:44:in `on'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/rest/handler.rb:9:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
/usr/local/bundle/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/aws_sdk.rb:31:in `block in call'
/usr/local/bundle/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/recorder.rb:120:in `capture'
/usr/local/bundle/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/aws_sdk.rb:28:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/usr/local/bundle/gems/aws-sdk-s3-1.57.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
/usr/local/bundle/gems/aws-sdk-s3-1.57.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
/usr/local/bundle/gems/aws-sdk-s3-1.57.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.82.0/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/bundle/gems/aws-sdk-s3-1.57.0/lib/aws-sdk-s3/client.rb:1110:in `copy_object'
```

**Comment by awssandra** [comment] 2019-12-02 21:44
Hi himberjack,

Is this the full stack trace? It looks like the call is failing in the AWS SDK not the X-Ray SDK. There seems to be something wrong with the call itself?

Here's the line of code at the bottom of the stack trace:
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L1110

**Comment by himberjack** [comment] 2019-12-03 08:15
@awssandra It happens only after I added the xray sdk to the ruby!

**Comment by awssandra** [comment] 2019-12-04 19:32
Hi himberjack,

Very interesting! Sorry to hear about the issue. Can you possibly supply a small snippet to repro the issue?

Thanks!
Sandra

**Comment by himberjack** [comment] 2019-12-04 20:36
S3.copy_object(
           bucket: 'xxxx',
          copy_source: "xxxx/yyyy",
           key: 'zzzzzzz'
         )

**Comment by awssandra** [comment] 2019-12-05 18:41
Hi himberjack,

Can you show us the snippets how/where you are using this call to S3? Where you are importing the SDK? Are you running in Lambda or non-Lambda?

**Comment by srprash** [comment] 2020-01-09 21:40
Closing this for now. Feel free to reopen.

**Closed by srprash** 2020-01-09 21:40 UTC

**Comment by alextwoods** [comment] 2021-03-30 21:49
I'm looking into this now - trying to get a reproduction but haven't been able to yet.

One workaround is to switch the XML engine you are using - some of them are more forgiving than others.  Based on the stacktrace, it looks like you have `nokogiri` loaded.  If you add `ox` to your Gemfile, the AWS SDK will pick it up and use `ox` as the engine and it is a bit more forgiving and is able to parse the xml from the stack trace you included.
